spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



---
spring:
  profiles: local
  redis:
    host: 127.0.0.1
    port: 6379
    password: password

server:
  port: 8080

---
spring:
  profiles: dev
  redis:
    host: 127.0.0.1
    port: 6379
    password: password

server:
  port: 8080

---
spring:
  profiles: prd
  redis:
    host: 127.0.0.1
    port: 6379
    password: password

server:
  port: 8080