spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

---
spring:
  profiles: local
  redis:
    host: 127.0.0.1
    port: 6379
    cluster:
      nodes: 127.0.0.1:6379
    password: password

---
spring:
  profiles: prd
  redis:
    host: 127.0.0.1
    port: 6379
    cluster:
      nodes: 127.0.0.1:6379
    password: password